### ISSUE TITLE
No error message

### ISSUE THREAD

**Issue by WlinkNET** [3Dpass/threedpass#43] opened 2023-04-20 08:33 UTC
If we try to import on android app any txt file we dont have any info on error just black bottom line maybe it will be nice to have error message and supported extensions

**Comment by L3odr0id** [comment] 2023-04-20 11:15
Thank you for idea! Could you please share the screenshot with "just black bottom line"? 
The app actually checks extensions. Only .obj and .stl are allowed. But there is no message about wrong extension. I'll consider adding it

**Comment by WlinkNET** [comment] 2023-04-20 11:19
![Screenshot_2023-04-20-13-17-26-794_com threedpass wallet](https://user-images.githubusercontent.com/52631720/233350732-8768693a-da96-4b74-be58-8e2f051840e4.jpg)

**Comment by L3odr0id** [comment] 2023-04-20 12:03
Thank you for information. That's strange behaviour. It should show the snackbar with the title 'No file selected', but your's is empty. I'll try to fix this

**Comment by L3odr0id** [comment] 2023-05-10 08:03
@WlinkNET, could you please check if the issue is fixed in 2.6.1?

**Comment by WlinkNET** [comment] 2023-05-10 09:50
![Screenshot_2023-05-10-11-48-49-502_com threedpass wallet](https://github.com/3Dpass/threedpass/assets/52631720/f089417f-8eba-48bc-b659-76759aacfa94)
Now just sai no file select is that ok? Or we need message selected file with {extension} is not supported?

**Comment by L3odr0id** [comment] 2023-05-10 09:53
That's OK. The message box isn't empty now. I'll consider adding the error message about supported extensions. Thank you!

**Closed by L3odr0id** 2023-05-10 09:53 UTC
Labels: enhancement, good first issue
